---
title: "DUMMY_DataAnalysis"
output: html_document
date: "2024-04-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

https://github.com/kamaulindhardt/V4F_agrivoltaics

# Preparing R script

Packages to be installed first

```{r Installing the pacman package, warning=FALSE}
install.packages("pacman")
#install.packages("tidyverse")
```

## Installing at loading packages and libraries needed

```{r Loading other needed packages, warning=FALSE}
suppressWarnings({

  # Applying the p_load function to load multiple add-on packages in one line of code.

  pacman::p_load(
    tidyverse,  # general package for everything
    readxl,     # reading excel data
    vroom,      # for crazy fast method of loading/reading datasets from local disc
    janitor,    # for cleaning data column names
    styler     # for neatly organising code
  )
})
```

```{r}
tdr_data <- read_excel("DATA/TDR.xlsx", 
                       sheet = "Sheet1")

tdr_data
```

```{r}
# Filter the data for the specific depths of 0.2 and 0.5 meters
filtered_data <- tdr_data %>%
  filter(`TDR Probe Rod Depth [m]` %in% c(0.2, 0.5))

# Create the boxplot
ggplot(filtered_data, aes(x = factor(`TDR Probe Rod Depth [m]`), y = `TDR Soil Water Measurement [%]`)) +
  geom_boxplot() +
  labs(x = "TDR Probe Rod Depth [m]", y = "Soil Water Measurement [%]") +
  ggtitle("TDR Soil Water Measurement by Probe Rod Depth") +
  theme_bw()
```

